## Python learning notebook

### Data Format
CSV format:

rows: information for a single patient

columns: successive days

![Alt text](../fig1.png "Optional title")

#### Basic data types in Python: 
integers, strings, and floating-point

Use print(something) and print(type(something)) to display the value and type of value of something.

Import a library into a program using import libraryname. Use the numpy library to work with arrays in Python.

In [166]:
import numpy as np

Ask the library to read our data file:

np.loadtxt(fname='name of file', delimiter='separates values on a line')

In [ ]:
data = np.loadtxt(fname='./data/inflammation-01.csv', delimiter=',')

Use variable = value to assign a value to a variable in order to record it in memory.

In [168]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


What type of thing data refers to.

In [169]:
print(type(data))

<class 'numpy.ndarray'>


An N-dimensional array.

The expression array.shape gives the shape of an array, and data.shape gives the type of the data contained in the NumPy array.

In [170]:
print(data.dtype)
print(data.shape)

float64
(60, 40)


Use array[x, y] to select a single element from a 2D array. Array indices start at 0, not 1.

![Alt text](../fig2.png "Optional title")

In [171]:
print('first value in data:', data[0, 0])
print('middle value in data:', data[29, 19])

first value in data: 0.0
middle value in data: 16.0


### Slicing data
select the first ten days (columns) of values for the first four patients (rows):

In [172]:
print(data[0:4, 0:10])

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


Start at index 0 and go up to, but not including index 4.

Start at index 5 (row 6) and go up to, but not including index 10 (row 11).

In [173]:
print(data[5:10, 0:10])

[[0. 0. 1. 2. 2. 4. 2. 1. 6. 4.]
 [0. 0. 2. 2. 4. 2. 2. 5. 5. 8.]
 [0. 0. 1. 2. 3. 1. 2. 3. 5. 3.]
 [0. 0. 0. 3. 1. 5. 6. 5. 5. 8.]
 [0. 1. 1. 2. 1. 3. 5. 3. 5. 8.]]


Selects rows 0 through 2 and columns 36 through to the end of the array.

In [174]:
small = data[:3, 36:]
print('small is:')
print(small)

small is:
[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


### Analyzing data:
To calculates the arithmetic mean (average) of all values in the NumPy array (data):

In [175]:
print(np.mean(data))

6.14875


It takes all 2400 values in the array (60 patients × 40 days), adds them all together, divides by the total number of values (2400), and then returns a single scalar value representing the overall average inflammation.

A sample function to show that all Python functions does not have input:

In [176]:
import time as ti
print(ti.ctime())

Mon Apr 21 11:44:51 2025


### Simple statistics:
numpy.mean(array): Mean

numpy.amax(array): maximum

numpy.amin(array): Minimum

In [177]:
maxval, minval, stdval = np.amax(data), np.amin(data), np.std(data)

print('maximum inflammation:', maxval)
print('minimum inflammation:', minval)
print('standard deviation:', stdval)

maximum inflammation: 20.0
minimum inflammation: 0.0
standard deviation: 4.613833197118566


In [178]:
patient_0 = data[0, :] # row 1, all columns
print('maximum inflammation for patient 0:', np.amax(patient_0))

maximum inflammation for patient 0: 18.0


In [179]:
print('maximum inflammation for patient 2:', np.amax(data[2, :]))

maximum inflammation for patient 2: 19.0


### Statistics across the specified axis:
numpy.mean(array, axis=0)

![Alt text](../fig3.png "Optional title")

By specifying axis=0, NumPy takes each column (day) and computes the mean of all 60 patient values for that day.

In [180]:
print(np.mean(data, axis=0))
print(np.mean(data, axis=0).shape)

[ 0.          0.45        1.11666667  1.75        2.43333333  3.15
  3.8         3.88333333  5.23333333  5.51666667  5.95        5.9
  8.35        7.73333333  8.36666667  9.5         9.58333333 10.63333333
 11.56666667 12.35       13.25       11.96666667 11.03333333 10.16666667
 10.          8.66666667  9.15        7.25        7.33333333  6.58333333
  6.06666667  5.95        5.11666667  3.6         3.3         3.56666667
  2.48333333  1.5         1.13333333  0.56666667]
(40,)


The result is a 1D array with 40 elements (N×1 vector-one average for each day).

numpy.mean(array, axis=1):

By specifying axis=1, NumPy takes each row (patient) and computes the mean of all 40 days values for that ptient. It should output 60 averaged values.

In [188]:
print(np.mean(data, axis=1))
print(np.mean(data, axis=1).shape)

[5.45  5.425 6.1   5.9   5.55  6.225 5.975 6.65  6.625 6.525 6.775 5.8
 6.225 5.75  5.225 6.3   6.55  5.7   5.85  6.55  5.775 5.825 6.175 6.1
 5.8   6.425 6.05  6.025 6.175 6.55  6.175 6.35  6.725 6.125 7.075 5.725
 5.925 6.15  6.075 5.75  5.975 5.725 6.3   5.9   6.75  5.925 7.225 6.15
 5.95  6.275 5.7   6.1   6.825 5.975 6.725 5.7   6.25  6.4   7.05  5.9  ]
(60,)


A section of an array is called a slice. We can take slices of character strings as well:

In [182]:
element = 'oxygen'
print('first three characters:', element[0:3])
print('last three characters:', element[3:6])

first three characters: oxy
last three characters: gen


### Staking arrays:
Arrays can be stacked on top of one another, using NumPy’s vstack and hstack functions for vertical and horizontal stacking, respectively.

In [183]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('A = ')
print(A)

A = 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [184]:
B = np.hstack([A, A])
print('B = ')
print(B)

C = np.vstack([A, A])
print('C = ')
print(C)

B = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]
C = 
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


Indlammation data of patient 3, week 1:

In [ ]:
patient3_week1 = data[2, :7]
print(patient3_week1)

[0. 0. 2. 0. 4. 2. 2.]


The following function takes an array and returns the differences between two successive values: [ 0 - 0, 2 - 0, 0 - 2, 4 - 0, 2 - 4, 2 - 2 ]. Then it returns the 6 difference values in a new array.

In [186]:
np.diff(patient3_week1)

array([ 0.,  2., -2.,  4., -2.,  0.])